export enum LOADING_STATUSES {
  NOT_STARTED = 'NOT_STARTED',
  LOADING = 'LOADING',
  SUCCESS = 'SUCCESS',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export const FINAL_LOADING_STATUSES = new Set([
  LOADING_STATUSES.CANCELLED,
  LOADING_STATUSES.FAILED,
  LOADING_STATUSES.SUCCESS,
]);
